version: '3'

services:
  database:
    container_name: delivery-api
    image: 'postgres:alpine'
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/var/lib/postgresql'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker

volumes:
  postgresql_data:
    driver: local
